#!/bin/sh

# Отлавливаем коммиты для ветки master
while read local_ref local_sha remote_ref remote_sha
do
  # Проверяем, является ли ветка master
  if [ "$remote_ref" = "refs/heads/master" ]; then
    echo "Запрещено пушить локальную ветку master в удаленную ветку master"
    exit 1
  fi
done

exit 0
undefined
